# Generated by Django 3.2.2 on 2021-05-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='text',
            name='text_data',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
