# Generated by Django 3.2.2 on 2021-05-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210512_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.CharField(max_length=300)),
                ('sentence_translation', models.CharField(max_length=600)),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_data',
        ),
        migrations.AddField(
            model_name='text',
            name='original_content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.AddField(
            model_name='sentence',
            name='Text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='posts.text'),
        ),
    ]
