# Generated by Django 3.2.8 on 2021-10-24 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='correction',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Elementary'), ('3', 'Intermediate'), ('4', 'Advanced'), ('5', 'Master')], default='beginner', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Elementary'), ('3', 'Intermediate'), ('4', 'Advanced'), ('5', 'Master')], default='beginner', max_length=15),
        ),
    ]
