# Generated by Django 3.2.2 on 2021-05-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210512_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
