# Generated by Django 3.2.8 on 2022-01-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211025_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correction',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='correction',
            name='score_comment',
            field=models.CharField(default='Great', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correction',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Elementary'), ('2', 'Beginner'), ('3', 'Intermediate'), ('4', 'Advanced'), ('5', 'Master')], default='en', max_length=15),
        ),
        migrations.AlterField(
            model_name='correction',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Elementary'), ('2', 'Beginner'), ('3', 'Intermediate'), ('4', 'Advanced'), ('5', 'Master')], default='en', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default='1', max_length=2),
        ),
    ]
