# Generated by Django 3.2.2 on 2021-05-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_delete_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to=settings.AUTH_USER_MODEL),
        ),
    ]
