# Generated by Django 3.2.8 on 2022-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220117_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='seen_by_author',
            field=models.BooleanField(default=False),
        ),
    ]
