# Generated by Django 3.2.2 on 2021-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='learning_language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default='unset', max_length=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='unset', max_length=15),
        ),
    ]
