# Generated by Django 3.2.8 on 2021-10-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Elementary'), ('3', 'Intermediate'), ('4', 'Advanced'), ('5', 'Master')], default='unset', max_length=15),
        ),
    ]
