# Generated by Django 3.2.8 on 2022-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('1', 'Elementary'), ('2', 'Beginner'), ('3', 'Intermediate'), ('4', 'Advanced'), ('5', 'Master')], default='unset', max_length=15),
        ),
    ]
